languages:
  Ruby: true
exclude_paths:
- "coverage/assets/0.10.0/application.js"
- "features/step_definitions/web_steps.rb"
- "config/initializers/form.rb"
- "config/webpack/app/assets/javascripts/common-bundle.js"
- "app/assets/javascripts/griddle.js"
- "bower_components"
- "app/frontend/old_javascripts_folder/griddle.js"
- "public/assets/main-bundle-c922606d11cfa251d8c9.js"
- "public/assets/bundle.js"
- "app/assets/javascripts/common-bundle.js"
- "app/assets/javascripts/bundle.js"


